export const ADD_INGREDIENT: "ADD_INGREDIENT" = "ADD_INGREDIENT";
export const DELETE_INGREDIENT: "DELETE_INGREDIENT" = "DELETE_INGREDIENT";
export const INCREASE_COUNTER: "INCREASE_COUNTER" = "INCREASE_COUNTER";
export const DECREASE_COUNTER: "DECREASE_COUNTER" = "DECREASE_COUNTER";
export const FILTER_INGREDIENTS: "FILTER_INGREDIENTS" = "FILTER_INGREDIENTS";
export const RESET_INGREDIENTS: "RESET_INGREDIENTS" = "RESET_INGREDIENTS";
