export const POST_ORDER_REQUEST: "POST_ORDER_REQUEST" = "POST_ORDER_REQUEST";
export const POST_ORDER_SUCCESS: "POST_ORDER_SUCCESS" = "POST_ORDER_SUCCESS";
export const POST_ORDER_ERROR: "POST_ORDER_ERROR" = "POST_ORDER_ERROR";
export const OPEN_MODAL_ORDER_DETAILS: "OPEN_MODAL_ORDER_DETAILS_MODAL" =
  "OPEN_MODAL_ORDER_DETAILS_MODAL";
export const CLOSE_MODAL_ORDER_DETAILS: "CLOSE_MODAL_ORDER_DETAILS" =
  "CLOSE_MODAL_ORDER_DETAILS";
export const RESET_INGREDIENTS: "RESET_INGREDIENTS" = "RESET_INGREDIENTS";
